.PHONY: help build push clean 

help:
	@echo "Available commands:"
	@echo "  make build            - Build the Docker container"
	@echo "  make push             - Push the Docker container to the registry"
	@echo "  make clean            - Clean up temporary test files"

build:
	@echo "Building pypi package"

push:
	@echo "Pushing pypi package to the registry"

clean:
	@echo "Cleaning up temporary files"

